version: '3'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
      - MONGODB_DATABASE=cq