server:
  port: 8080
  
security:
  token:
    secret:
      key: Asjfwol2asf123142Ags1k23hnSA36as6f4qQ324FEsvb

spring:
  data:
    mongodb:
      database: cq
      password: admin
      username: admin
      host: localhost
      port: 27017
#      uri: ${MONGODB_URI}


